services:
  - type: web
    name: renmukti-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        fromEnvVar: MONGODB_URI
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
